name: HydrogenSO Build CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 1. Adicionamos xorriso e grub-pc-bin na lista de dependências
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-multilib nasm make xorriso grub-pc-bin grub-common mtools

    - name: Compile Kernel
      run: |
        make clean
        make kernel.elf

    # 2. Criamos a estrutura de pastas do GRUB e geramos o .iso mágico
    - name: Generate Bootable ISO
      run: |
        mkdir -p isodir/boot/grub
        cp kernel.elf isodir/boot/hydrogen.elf
        echo 'menuentry "HydrogenSO" {' > isodir/boot/grub/grub.cfg
        echo '  multiboot /boot/hydrogen.elf' >> isodir/boot/grub/grub.cfg
        echo '}' >> isodir/boot/grub/grub.cfg
        grub-mkrescue -o hydrogenso.iso isodir

    # 3. Fazemos o upload do .iso gerado em vez do .elf
    - name: Upload ISO Binary
      uses: actions/upload-artifact@v4
      with:
        name: hydrogenso-iso
        path: hydrogenso.iso
